{
    "name": "Real Estate Purchase",
    "version": "1.0.0",
    "summary": "Create POs from Real Estate records; map lines to purchase.order",
    "category": "Custom",
    "author": "Generated by ChatGPT",
    "license": "LGPL-3",
    "depends": ["base", "product", "stock", "account", "purchase"],
    "data": [
        "data/sequence.xml",
        "security/ir.model.access.csv",
        "views/product_views.xml",
        "views/purchase_order_view.xml",
        "views/real_estate_views.xml",
        "views/stock_picking_views.xml",
        "views/master_views.xml",
        "views/menu_views.xml",
        "reports/real_estate_purchase_order_templates.xml",
        "reports/real_estate_purchase_order_report.xml",
        'reports/report_grn.xml',
    ],
    "installable": True,
    "application": False
}
